### ISSUE TITLE
预计何时发布测试版本

### ISSUE THREAD

**Issue by amokiel** [yleencc/pixgem-flutter#2]
好像已经过去了很久，开发者辛苦了。什么时候可以考虑发布测试版本呢？多谢！

**Comment by yleencc** [comment]
鸽了（
时间过的真快，六月底才从学校一堆琐事中解放出来，然后近期在研究组装新电脑，~~还加班~~，一个月不知不觉就没了。
不会弃坑，就是开发比较慢。

**Comment by yleencc** [comment]
> 好像已经过去了很久，开发者辛苦了。什么时候可以考虑发布测试版本呢？多谢！

鸽了（
时间过的真快，六月底才从学校一堆琐事中解放出来，然后近期在研究组装新电脑，还加班，一个月不知不觉就没了。
不会弃坑，就是开发比较慢。

**Comment by asadahimeka** [comment]
@amokiel ,可以用 [Github Actions](https://github.com/asadahimeka/pixiv-artvier/blob/main/.github/workflows/ci.yml) 打包尝尝鲜，我自己打了个[包](https://github.com/asadahimeka/pixiv-artvier/suites/16237839149/artifacts/927425696)体验了下感觉很不错，感谢作者的开发，期待作者的后续完善。

**Comment by jilebaobao** [comment]
2024年了开发者辛苦了什么时候等到测试版本😭😭

**Comment by yleencc** [comment]
> 2024年了开发者辛苦了什么时候等到测试版本😭😭

近期在写了，刚搞了直连，还需要再补充一些基本功能，下个月应该能出个版。

**Comment by jilebaobao** [comment]
好的！您辛苦了
